- hosts: localhost
  vars_files:
      - secret.yml
  tasks:
   - name: Provision os in AWS
     ec2:
      key_name: "KEY_NAME"
      instance_type: "t2.micro"
      image: "ami-0ebc1ac48dfd14136"
      count: 1
      wait: yes
      vpc_subnet_id: "SUBNET_ID"
      region: "ap-south-1"
      state: present
      assign_public_ip: yes
      group_id: "SECURITY_GROUP_ID"
      aws_access_key: "{{ myuser }}"
      aws_secret_key: "{{ mypass }}"
     register: ec2
     when :

   - debug:
       var: ec2.instances[0].public_ip

===== extra =====
   - name: Adding the instance in host group
     add_host:
       hostname: "{{ item.public_ip }}"
       groupname: ec2Group
     with_items: "{{ ec2.instances }}"

   - name: Wait till configuration of SSH
     wait_for:
        host: "{{ item.public_ip }}"
        port: 22
        state: started
     with_items: "{{ ec2.instances }}"
===== extra =====

- hosts: ec2Group
  become: yes
  remote_user: ec2-user
  tasks:

      - name: Download Httpd and Git in remote system
        package:
         name:
           - httpd
           - git
         state: present

      - name: Clone code from GitHub
        git:
         repo: 'REPO_URL'
         dest: "/var/www/html/"


      - name: start the services of httpd
        service:
         name: "httpd"
         state: restarted
